name: Ci/CD pipeline 

on:
  push:
    branches:
     - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu 
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /home/ubuntu/ci-cd-learning-
            git pull 
            docker compose up -d --build 
